#!/bin/bash

n1=1
n2=20

echo ' '
sum=0

for i in $(seq $n1 $n2)
do
if [[ $((i % 2)) -eq 0 ]]
then
echo 'Sum = '$sum' + '$i
sum=$((sum+i))
fi
done
echo ' '
echo 'The result of sum of even numbers between 1 and 20 is '$sum 
